server:
  port: 9000

spring:
  application:
    name: gateway

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: client-one
          #转发的地址,写服务名称
          uri: lb://CLIENT-ONE
          predicates:
          - Path=/clientOne/**

          #去掉Path前缀,参数为1代表去掉/clientOne
          filters:
          - StripPrefix=1

        - id: client-two
          uri: lb://CLIENT-TWO
          predicates:
          - Path=/clientTwo/**
          filters:
          - StripPrefix=1

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8181/eureka
  # 将IP注册到Eureka Server上
  instance:
    prefer-ip-address: true


#为feign开启断路器
#feign:
#  hystrix:
#    enabled: true
#  client:
#    config:
#      default:
#        connectTimeout: 30000
#        readTimeout: 30000
#        loggerLevel: full
#        retryer:
#          maxAttempts: 3
#          period: 1000
#          maxPeriod: 10000
