server:
  port: 9000

spring:
  application:
    name: gateway

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.96.130:3306/moon_test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true&tinyInt1isBit=false
    username: root
    password: Long123_@456
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5  # 初始化大小
      min-idle: 5  # 最小
      max-active: 100  # 最大
      max-wait: 60000  # 配置获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000  # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      min-evictable-idle-time-millis: 300000  # 指定一个空闲连接最少空闲多久后可被清除，单位是毫秒
      validationQuery: select 'x'
      test-while-idle: true  # 当连接空闲时，是否执行连接测试
      test-on-borrow: false  # 当从连接池借用连接时，是否测试该连接
      test-on-return: false  # 在连接归还到连接池时是否测试该连接
      filters: config,wall,stat  # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      poolPreparedStatements: true # 打开PSCache，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20
      maxOpenPreparedStatements: 20

  redis:
    host: 192.168.142.128
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 8
        max-idle: 500
        min-idle: 0


  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: client-one
          #转发的地址,写服务名称
          uri: lb://CLIENT-ONE
          predicates:
          - Path=/clientOne/**
          #去掉Path前缀,参数为1代表去掉/clientOne
          filters:
          - StripPrefix=1

        - id: client-two
          uri: lb://CLIENT-TWO
          predicates:
          - Path=/clientTwo/**
          filters:
          - StripPrefix=1



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8181/eureka
    fetch-registry: true
  # 将IP注册到Eureka Server上
  instance:
    prefer-ip-address: true
#    appname: ${spring.application.name}
