server:
  port: 8989

spring:
  application:
    name: zuul



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8181/eureka
    fetch-registry: true
  # 将IP注册到Eureka Server上
  instance:
    prefer-ip-address: true
#    appname: ${spring.application.name}


#为feign开启断路器
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 30000
        readTimeout: 30000
        loggerLevel: full
        retryer:
          maxAttempts: 3
          period: 1000
          maxPeriod: 10000

zuul:
  intelligentsia-authority:
    ignoredHeaders: Authorization
  routes:
    client-one:
      path: /con/**
      serviceId: client-one
      stripPrefix: true
      sensitiveHeaders:
    client-two:
      path: /two/**
      serviceId: client-two
      stripPrefix: true
      sensitiveHeaders:
    sso:
      path: /sso/**
      serviceId: sso
      stripPrefix: true
      sensitiveHeaders:

ribbon:
  ReadTimeout: 120000  #请求处理的超时时间
  ConnectTimeout: 30000  #请求连接的超时时间




security:
  oauth2:
    resource:
      tokenInfoUri: http://localhost:8800/oauth/check_token
      preferTokenInfo: true
      jwt:
        key-uri: localhost:8800/oauth/token_key

    client:
      accessTokenUri: http://localhost:8800/oauth/token
      userAuthorizationUri: http://localhost:8800/oauth/authorize
      clientId: abc
      clientSecret: long
      grant-type: password
      access-token-uri: http://localhost:8800/oauth/token


